Repository prgrms-be-devcourse/NBE1_2_Team01, pull requests merged in 2024-10, with the labels that each got.

#70 feat: #68 관리자 체크 api 구현
  src/main/java/org/team1/nbe1_2_team01/domain/user/controller/api/UserController.java
  src/main/java/org/team1/nbe1_2_team01/domain/user/service/UserService.java
  src/main/java/org/team1/nbe1_2_team01/domain/user/service/response/UserAdminCheckResponse.java
  src/main/java/org/team1/nbe1_2_team01/domain/user/util/UserConverter.java
Labels: 💧 순한맛, Feat, 믿음

#72 feat: #61 페이징 정보 제공하는 api 추가
  src/main/java/org/team1/nbe1_2_team01/domain/board/controller/CourseBoardController.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/repository/CustomCourseBoardRepository.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/repository/CustomCourseBoardRepositoryImpl.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/service/CourseBoardService.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/service/CourseBoardServiceImpl.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/service/response/CourseBoardResponse.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/service/response/PagingResponse.java
Labels: 🔥 매운맛, Feat, Chore, 준호

#75 FEAT : 채팅 참여하기 응답 값 수정
  src/main/java/org/team1/nbe1_2_team01/domain/chat/controller/ParticipantController.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/service/ParticipantService.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/service/response/ParticipantResponse.java
  src/main/resources/dummy/dummy.sql
Labels: Chore, 희수

#76 Refactor/#67 회원 테스트 수정
  .gitignore
  src/main/java/org/team1/nbe1_2_team01/global/config/WebSocketConfig.java
  src/test/java/org/team1/nbe1_2_team01/domain/user/controller/UserControllerTest.java
  src/test/java/org/team1/nbe1_2_team01/domain/user/service/UserServiceTest.java
  src/test/resources/application-test.yaml
Labels: 💧 순한맛, Feat, 믿음

#79 Feat: #78 로그인한 사용자가 소속된 팀 목록 조회 기능 구현
  src/main/java/org/team1/nbe1_2_team01/domain/group/controller/TeamController.java
  src/main/java/org/team1/nbe1_2_team01/domain/group/repository/BelongingRepository.java
  src/main/java/org/team1/nbe1_2_team01/domain/group/service/TeamService.java
Labels: 💧 순한맛, Feat, 민우

#84 Refactor/#82 토큰 발급 리팩토링
  src/main/java/org/team1/nbe1_2_team01/domain/user/controller/api/UserController.java
  src/main/java/org/team1/nbe1_2_team01/domain/user/service/UserService.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/email/repository/EmailRepository.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/email/service/EmailService.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/email/token/EmailToken.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/jwt/respository/RefreshTokenRepository.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/jwt/service/JwtService.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/jwt/token/RefreshToken.java
  src/main/java/org/team1/nbe1_2_team01/global/config/SecurityConfig.java
  src/main/java/org/team1/nbe1_2_team01/global/util/ErrorCode.java
  src/test/java/org/team1/nbe1_2_team01/domain/user/controller/UserControllerTest.java
Labels: 💧 순한맛, Refactor, Chore, 믿음

#86 팀 생성 관련 테스트 코드 작성
  src/main/java/org/team1/nbe1_2_team01/domain/board/controller/dto/CategoryRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/controller/dto/CourseBoardRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/controller/dto/TeamBoardRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/board/service/CourseBoardServiceImpl.java
  src/main/java/org/team1/nbe1_2_team01/domain/group/controller/request/TeamApprovalUpdateRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/group/controller/request/TeamCreateRequest.java
  src/main/java/org/team1/nbe1_2_team01/global/config/SecurityConfig.java
  src/test/java/org/team1/nbe1_2_team01/domain/group/service/TeamServiceTest.java
  src/test/java/org/team1/nbe1_2_team01/domain/user/controller/UserControllerTest.java
  src/test/java/org/team1/nbe1_2_team01/domain/user/service/UserServiceTest.java
Labels: 💧 순한맛, Feat, 민우

#88 Refatcor/#87 이메일 전송 리팩토링
  build.gradle
  src/main/java/org/team1/nbe1_2_team01/Nbe12Team01Application.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/email/service/EmailService.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/email/util/EmailUtil.java
  src/main/java/org/team1/nbe1_2_team01/global/config/AsyncConfig.java
  src/main/java/org/team1/nbe1_2_team01/global/config/RetryConfig.java
Labels: 💧 순한맛, Refactor, Chore, 믿음

#89 FEAT : 채팅에 상태코드 추가, 및 이모지 관련 메소드 & 파일 추가
  src/main/java/org/team1/nbe1_2_team01/domain/chat/controller/ChatController.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/controller/EmoticonController.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/controller/request/ChatMessageRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/controller/request/EmoticonMessageRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/controller/request/InviteRequest.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/entity/Chat.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/entity/ChatActionType.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/service/ChatService.java
  src/main/java/org/team1/nbe1_2_team01/domain/chat/service/ParticipantService.java
  src/main/resources/static/emoticons/1.jpg
  src/main/resources/static/emoticons/2.jpg
  src/main/resources/static/emoticons/3.jpg
Labels: Feat, Chore, 희수

#92 Hotfix/#91 오류 수정
  src/main/java/org/team1/nbe1_2_team01/global/auth/email/service/EmailService.java
  src/main/java/org/team1/nbe1_2_team01/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/org/team1/nbe1_2_team01/global/config/MailConfig.java
  src/main/resources/application.yaml
Labels: 💧 순한맛, Fix, 믿음
